### ISSUE TITLE
showing in all sites

### ISSUE THREAD

**Issue by swyxio** [tsriram/is-gatsby#1]
chrome must have changed something... now the icon is lighting up on all sites:

![image](https://user-images.githubusercontent.com/6764957/50644147-f3c2d600-0faa-11e9-9bf7-d0ec5fdf4754.png)

unless github is using gatsby then something has broken in chrome...

**Comment by tsriram** [comment]
@sw-yx I went for the workaround with separate gray icon for pages that don't use Gatsby. Looks like react & redux devtools do similarly. Just published the new version of extension and it should be up soon.

**Comment by swyxio** [comment]
ugh. but we should also tell chrome they introduce a regression for no reason...
